#!/bin/bash
#Инсталятор скрипта резервного копирования


##############################
###  ТОЧКА СТАРТА СКРИПТА  ###
##############################

#Определяем путь запуска скрипта
# current path resolver from http://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
INSTALL_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#Считываем основные параметры настроек из файла config.cfg
. $INSTALL_DIR/config.cfg

echo "Проверьте настройки скрипта резервного копирования:"
echo " 1: Путь расположения скрипта: "$INSTALL_DIR
echo " 2: Имя пользователя под которым будет выполнятся скрипт: "$USER
echo " 3: Логфайл сессии резервного копирования: "$BackupLog
echo " 4: Логфайл ошибок сессии резервного копирования: "$ErrorLog
echo " 5: Логфайл ощибок доставки сообщений о сбоях скрипта резервного копирования: "$ErrorNotifyLog
echo " 6: Получатель сообщений о ошибках скрипта резервного копирования: "$NotifyDestination
echo ""
echo "Если настройки верны и вы хотите продолжить установку нажните /y/"
read item
case "$item" in
   	y|Y) echo "Ввели «y», продолжаем..."
       	;;
   	n|N) echo "Ввели «n», завершаем..."
       	exit 1
       	;;
   	*) echo "Ничего не ввели. Выполняем действие по умолчанию... (заканчиваем работу)"
		exit 1
       	;;
esac


#Создаем логфайл сессии резервного копирования
echo "проверяем сущестует ли такой файл "$BackupLog

if [ -a $BackupLog ]
then
	echo "Файл с таким именем уже существует."
	exit 1
fi
#Создание файла лога сессии резервного копирования 
`cat</dev/null>$BackupLog`
if [ -a $BackupLog ] 
then
	echo "Файл "$BackupLog" успешно создан"
else
	echo "Не получается создать файл с именем "$BackupLog
	exit 1
	
fi
# Задаем права на чтение и редактирование для всех (666) на логфайл сессии резервного копирования
`chmod 666 $BackupLog`
if [ $? -ne 0 ];
then 
	echo "Не удается задать права на логфайл "$BackupLog
	exit 1
fi


#Создаем логфайл ошибок сессии резервного копирования
echo "проверяем сущестует ли такой файл "$ErrorLog

if [ -a $ErrorLog ]
then
	echo "Файл с таким именем уже существует."
	exit 1
fi
#Создание файла лога сессии резервного копирования 
#
`cat</dev/null>$ErrorLog`
if [ -a $ErrorLog ]; 
then
	echo "Файл "$ErrorLog" успешно создан"
else
	echo "Не получается создать файл с именем "$ErrorLog
	exit 1
	
fi
# Задаем права на чтение и редактирование для всех (666) на логфайл ошибок сессии резервного копирования
`chmod 666 $ErrorLog`
if [ $? -ne 0 ];
then 
	echo "Не удается задать права на логфайл "$ErrorLog
	exit 1
fi


#Создаем логфайл ошибок доставки сообщений о сбоях скрипта резервного копирования
echo "Проверяем сущестует ли такой файл "$ErrorNotifyLog

if [ -a $ErrorNotifyLog ]
then
	echo "Файл с таким именем уже существует."
	exit 1
fi
#Создание ошибок доставки сообщений о сбоях скрипта резервного копирования 
#
`cat</dev/null>$ErrorNotifyLog`
if [ -a $ErrorNotifyLog ]; 
then
	echo "Файл "$ErrorNotifyLog" успешно создан"
else
	echo "Не получается создать файл с именем "$ErrorNotifyLog
	exit 1
	
fi
# Задаем права на чтение и редактирование для всех (666) на логфайл ошибок нотификации резервного копирования
`chmod 666 $ErrorNotifyLog`
if [ $? -ne 0 ];
then 
	echo "Не удается задать права на логфайл "$ErrorNotifyLog
	exit 1
fi


#Задаем рекурсивно права на каталог установки скрипта резервного копирования и всех сопустствующих файлов
#Для всех фалов кроме ./FileBackup права 600 владелец root
#для ./FileBackup - 500 владелец $USER
echo "Задаем права на каталог установки скрипта: "$INSTALL_DIR
if [ -d $INSTALL_DIR ] && [ -a $INSTALL_DIR/FileBackup ]
then
	`chmod -R 600 $INSTALL_DIR`
	if [ $? -ne 0 ];
	then 
		echo "Не удается задать права каталог установки скрипта: "$INSTALL_DIR
		exit 1
	fi

	`chown -R $USER $INSTALL_DIR`
	if [ $? -ne 0 ];
	then 
		echo "Не удается задать владельцем каталога установки скрипта ("$INSTALL_DIR") пользователя root"
		exit 1
	fi

	`chmod 500 $INSTALL_DIR/FileBackup`
	if [ $? -ne 0 ];
	then 
		echo "Не удается задать права на выполнение для файла скрипта скрипта: "$INSTALL_DIR"/FileBackup"
		exit 1
	fi
else
	echo "Не удалось правильно определить каталог установри скрипта: "$INSTALL_DIR
	exit 1
fi


#Помогаем повесить задание в CRON
echo ""
echo "Для выполнения этого скрипта требуется добавить задание cron от того пользователя,"
echo "от которого будет выполняться."
echo "Для выполнения задания на резервное копироваения ежедневно в 23.30 требуетcя в crontab"
echo "добваить следующую строку:"
echo "30 23 * * * "$INSTALL_DIR"/FileBackup"
echo ""
echo "Если надо скопируйте эту строку для того чтобы добавить ее в crontab"
read -p "Для продолжения нажмите Enter и откроется crontab текущего пользователя "$USER" ..."
`crontab -u $USER -e`

exit 0












