#!/bin/bash

#Проверяем что надо сделать: установка параметров или осуществить уведомление
#Если переменная WorkMission="work" то выполняем уведомление
#Если переменная WorkMission="setup" то выполняем настройку параметров
#Если переменная WorkMission неопределена то случайный запуск

if [ ! $WorkMission ]; then
	echo "Этот скрипт не предназначен для самостоятельной работы"
elif [ $WorkMission == "work" ]; then
	#Далее выполнение уведомления

elif [ $WorkMission == "start" ]; then
		#Далее настраиваем скрипт
	#Все настройки дописываем в виде переменных в файл $INSTALL_DIR/config.cfg

fi



##Настройки модуля нотификации Email-noPassword

#Адрес отправителя
#EmailSender=""

#Адрес получателя
#EmailDestination=""

#Тема сообщения (Сюда следует завести имя компании и имя сервера)
#Пример: SubjectMessage="Рога и копыта: STORAGE"
#SubjectMessage=""



#ErrorLog="/var/log/FileBackupERROR.log"

#echo "Subject: "$SubjectMessage":Ошибка задания резервного копирования "$ArchFullName"( "$SrcPath" )\nFrom: "$EmailSender"\nTo: "EmailDestination"\n\n"| cat $ErrorLog > ./temp



#echo "Subject: Проверочка" > mail.txt 
#echo "From: admin123@cross-way.ru" >> mail.txt
#echo "To: andrey@admik.ru" >> mail.txt 
#echo "Тестовое сообщение" >> mail.txt
#echo "" >> mail.txt
#echo "NOiuhwdblckfsud" >> mail.txt
# cat ./mail.txt | /usr/sbin/sendmail -t
